languageCode = "en-US"
layoutdir = "layouts"
baseurl = "/"
googleAnalytics = ""
theme = "hugo-vitae"
publishDir = "deann88.github.io"

[params]
  author = "Deyan Spasov"
  title = "Deyan Spasov's Resume"
  description = "Deyan Spasov's Resume"
  avatar = "profile.png"
  email = "deyan.s.spasov@gmail.com"
  email_full = "mailto:deyan.s.spasov@gmail.com"
  twitter = "DeanSpasov"
  linkedin = "deanspasov"
  website = "datakubism.com"
  google_maps = "https://www.google.bg/maps/search/zh.k.+Yavorov+/@42.6831665,23.3504484,18.79z"
  address = "zh.k. Yavorov"
  postcode = "1111"
  city = "Sofia"
  country = "Bulgaria"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
